sudo: required
language: go
services:
  - docker
go:
  - 1.8.x
install:
  - set -e
  - ( cd vendor/code.cloudfoundry.org/cli && bin/build )
  - mv vendor/code.cloudfoundry.org/cli/out/cf "$GOPATH/bin"
script:
  - [[ -z $(bin/format | tee >(cat >&2)) ]]
  - bin/test -nodes=2 -compilers=2
