sudo: required
language: go
services:
  - docker
go:
  - 1.8.x
install:
  - set -e
  - curl -L https://cli.run.pivotal.io/stable?release=linux64-binary | tar -C "$GOPATH/bin" -xz cf
script:
  - test -z "$(bin/format | tee >(cat >&2))"
  - bin/test -nodes=2 -compilers=2
