required = [
  # Utilities
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/golang/mock/mockgen",
]

ignored = [
  "github.com/sclevine/forge",
  "github.com/sclevine/forge/*",
]

# App

[[constraint]]
  name = "github.com/fsnotify/fsevents"
  branch = "master"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/nu7hatch/gouuid"
  branch = "master"

# Test

[[constraint]]
  name = "github.com/onsi/ginkgo"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
